<?php

/**
 * Implementation of hook_permission().
 */
function search_by_argument_permission() {
  return array(
    'access search by argument' => array(
        'title' => 'Access argument search',
        'description' => 'Allows a user to access search results',
      )
    );
}

/**
 * Implementation of hook_menu().
 */
function search_by_argument_menu() {
  $items["mysearch/%"] = array(
    'title' => 'Search results',
    'page callback' => 'search_by_argument_search_page',
    'page arguments' => array(1),
    'access arguments' => array('access search by argument'),
  );
  return $items;
}

/*
 * Implementation of hook_theme().
 */
function search_by_argument_theme(){
  return array(
      'mysearch_page_result' => array(
          'template' => 'search-by-argument-page-result',
          'path' => drupal_get_path('module', 'search_by_argument') . '/theme',
      ),
  );
}


/**
 * Menu callback provides a simple list of nodes matching the
 * search term Example: hitting the URL:
 *   http://domain.com/mysearch/example
 * will return a list of links to nodes which have the word
 * example in them.
 */
function search_by_argument_search_page($search_term) {
  $query = db_select('node', 'n');
  $query->innerjoin('field_data_body', 'b', 'b.entity_id = n.nid');
  $query->fields('n', array('title', 'nid'));
  $query->condition('b.body_value', '%' . db_like($search_term) . '%', 'LIKE');
  $result = $query->execute()->fetchAll();
  return theme('mysearch_page_result', array('search_term' => $search_term, 'nodes' => $result));
}